= Apicurio GitHub Bot

== Introduction

This GitHub App is based on the https://github.com/quarkiverse/quarkus-github-app[Quarkus GitHub App framework].

It was forked from https://github.com/quarkusio/quarkus-github-bot[Quarkus GitHub Bot], and modified for the purposes of the Apicurio projects.

It can be run as a native executable.

== Current Actions

=== Triage Issues

Based on the `.github/apicurio-bot.yml` file, this rule affects labels to issues and also pings the appropriate people.

=== Triage Pull Requests

The pull requests triage action uses the same configuration file as the issues triage action.

== Contributing

To participate to the development of this GitHub App, create a playground project in your own org and
follow the steps outlined in https://quarkiverse.github.io/quarkiverse-docs/quarkus-github-app/dev/index.html[the Quarkus GitHub App documentation].

GitHub permissions required:

* Contents - `Read only`
* Issues - `Read & Write`
* Pull Requests - `Read & Write`

Events to subscribe to:

* Issues
* Pull Request

By default, in dev mode, the Bot runs in dry-run so it's logging its actions but do not perform them.
You can override this behavior by adding `_DEV_APICURIO_BOT_DRY_RUN=false` to your `.env` file.

== Deployment

TODO

== License

This project is licensed under the Apache License Version 2.0.
